# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  repository_dispatch:
    type: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Passed
        if: (github.event_name == 'repository_dispatch') && (github.event.client_payload.result == 'pass')
        run: |
          echo "DEPLOY!"
      
      - name: Files
        if: (github.event_name == 'repository_dispatch') && (github.event.client_payload.result == 'fail')
        run: |
          echo "Failed!"
          exit 1
