# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  repository_dispatch:
    type: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          echo "event_name: '${{ github.event_name }}'"
          echo "Received request from '${{ github.event.client_payload.repository }}'"
          echo "Test environment: '${{ github.event.client_payload.environment }}'"
          echo "Result: '${{ github.event.client_payload.result }}'"
    
      - name: Passed
        if: (github.event_name == 'repository_dispatch') && (github.event.client_payload.result == 'pass')
        run: |
          echo "DEPLOY!"
      
      - name: Failed
        if: (github.event_name == 'repository_dispatch') && (github.event.client_payload.result != 'pass')
        run: |
          echo "Failed!"
          exit 1
