name: E2E Tests - Production

#on:
#  repository_dispatch:
#    type: [ e2e_test_result_production ]

jobs:
  results:
    runs-on: ubuntu-latest
    steps:
      - name: Passed
        if: (github.event.client_payload.result == 'success')
        run: |
          echo "Production environment E2E tests passed"
      
      - name: Failed
        if: (github.event.client_payload.result != 'success')
        run: |
          echo "Production environment E2E tests failed"
          exit 1
