name: E2E Tests - Production

on:
  repository_dispatch:
    type: [ e2e-test-result-production ]

jobs:
  results:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          echo "Event type: '${{ github.event.event_type }}'"
          echo "Received request from '${{ github.event.client_payload.repository }}'"
          echo "Environment: '${{ github.event.client_payload.environment }}'"
          echo "Result: '${{ github.event.client_payload.result }}'"

      - name: Passed
        if: (github.event.client_payload.result == 'success')
        run: |
          echo "Production environment E2E tests passed"
      
      - name: Failed
        if: (github.event.client_payload.result != 'success')
        run: |
          echo "Production environment E2E tests failed"
          exit 1
