name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  setvar:
    runs-on: ubuntu-latest
    outputs:
      var1: ${{ steps.set_var.outputs.var1 }}
    steps:
      - name: set-var
        id: set_var
        run: |
          VAR1=${{ github.event_name }}
          echo "VAR1=${VAR1}"
          echo "::set-output name=var1::${VAR1}"

          echo "VAR2=env-var-2" >> $GITHUB_ENV

  use-output:
    needs: setvar
    runs-on: ubuntu-latest
    steps:
      - name: use-output
        run: |
          echo "OUTPUT=${{ needs.setvar.outputs.var1 }}"

  call-test-job:
    needs: setvar
    uses: joshxjin/experiments/.github/workflows/test-job.yaml@main
    with:
      input_var_1: '${{ needs.setvar.outputs.var1 }}-call'
      input_var_2: ${{ env.VAR2 }}
