name: Test Job 1

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Test Job
    runs-on: ubuntu-latest
    defaults:
      run:
        # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
        shell: bash

    steps:
      - name: checkout repo - current branch
        uses: actions/checkout@v2

      - name: Build Version
        id: buildVersion
        uses: ./.github/actions/build
        with:
          hub: "hub string"
          creds: ${{secrets.CREDS}}
          pat: ${{secrets.PAT}}
