name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  set-var:
    runs-on: ubuntu-latest
    outputs:
      var1: ${{ steps.set_var.outputs.var1 }}
    steps:
      - name: set-var
        id: set_var
        run: |
          VAR1=${{ github.event_name }}
          echo "VAR1=${VAR1}"
          echo "::set-output name=var1::${VAR1}"

  call-test-job:
    needs: set-var
    uses: joshxjin/experiments/.github/workflows/test-job.yaml@main
    with:
      input_var_1: '${{ needs.trigger.outputs.var1 }}'
      input_var_2: 'var2-call'
