# This is a basic workflow to help you get started with Actions

name: Trigger Repo Dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        default: 'development'
        required: true
        type: string
      continue_deployment:
        description: 'Allow continue deployment to the next environment if E2E test passed'
        default: true
        required: true
        type: boolean
    workflow_call:
      inputs:
        environment:
          description: 'Environment'
          required: true
          type: string
        continue_deployment:
          description: 'Allow continue deployment to the next environment if E2E test passed'
          required: true
          type: boolean
    secrets:
      PAT:
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Trigger
        run: |
          RETURN_EVENT_TYPE=`[ ${{ github.event.inputs.continue_deployment || inputs.continue_deployment }} == 'true' ] && echo deploy`
          echo $RETURN_EVENT_TYPE

          curl -X POST https://api.github.com/repos/joshxjin/experiments-2/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Authorization: Bearer ${{ secrets.PAT }}' \
          --data '{"event_type": "on_demand", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "environment": "${{ github.event.inputs.environment || inputs.environment }}", "'"${RETURN_EVENT_TYPE}"'" }}'
